id: seven_login
weight: 10
status: true
uuid: 1c03359c-1d4e-496b-902e-46b1178d40d7
langcode: en
dependencies:
  module:
    - user
  theme:
    - seven
theme: seven
region: content
plugin: user_login_block
settings:
  id: user_login_block
  label: 'User login'
  provider: user
  label_display: visible
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
