id: bartik_search
weight: -1
status: true
uuid: e2e3541f-5836-44b3-9f00-e2e8d8935e57
langcode: en
dependencies:
  module:
    - search
  theme:
    - bartik
theme: bartik
region: sidebar_first
plugin: search_form_block
settings:
  id: search_form_block
  label: Search
  provider: search
  label_display: visible
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
