id: bartik_powered
weight: 10
status: true
uuid: aa49ea6a-db65-4e60-aa00-a57e439959f1
langcode: en
dependencies:
  module:
    - system
  theme:
    - bartik
theme: bartik
region: footer
plugin: system_powered_by_block
settings:
  id: system_powered_by_block
  label: 'Powered by Drupal'
  provider: system
  label_display: '0'
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
