id: seven_help
weight: 0
status: true
uuid: d2039608-99a1-4362-8f09-099771520c8d
langcode: en
dependencies:
  module:
    - system
  theme:
    - seven
theme: seven
region: help
plugin: system_help_block
settings:
  id: system_help_block
  label: 'System Help'
  provider: system
  label_display: '0'
  cache:
    max_age: -1
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
