id: bartik_content
weight: 0
status: true
uuid: 11a999a5-90a3-4be1-982d-45f101ebfb87
langcode: en
dependencies:
  module:
    - system
  theme:
    - bartik
theme: bartik
region: content
plugin: system_main_block
settings:
  id: system_main_block
  label: 'Main page content'
  provider: system
  label_display: '0'
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
