id: seven_content
weight: 0
status: true
uuid: 483e75e6-87d5-4b7c-8108-8ee0b47128ba
langcode: en
dependencies:
  module:
    - system
  theme:
    - seven
theme: seven
region: content
plugin: system_main_block
settings:
  id: system_main_block
  label: 'Main page content'
  provider: system
  label_display: '0'
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
