id: bartik_tools
weight: 0
status: true
uuid: a5e51a52-c5a3-4e20-9800-b61d091718be
langcode: en
dependencies:
  entity:
    - system.menu.tools
  module:
    - system
  theme:
    - bartik
theme: bartik
region: sidebar_first
plugin: 'system_menu_block:tools'
settings:
  id: 'system_menu_block:tools'
  label: Tools
  provider: system
  label_display: visible
  cache:
    max_age: -1
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
