id: bartik_login
weight: 0
status: true
uuid: 74d8e607-b3fa-4c2e-a709-9a08fc11b36e
langcode: en
dependencies:
  module:
    - user
  theme:
    - bartik
theme: bartik
region: sidebar_first
plugin: user_login_block
settings:
  id: user_login_block
  label: 'User login'
  provider: user
  label_display: visible
  cache:
    max_age: 0
    contexts: {  }
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
