id: theme.bartik.narrow
name: narrow
label: narrow
mediaQuery: 'all and (min-width: 560px) and (max-width: 850px)'
source: bartik
sourceType: theme
weight: 1
multipliers:
  1x: 1x
status: true
uuid: 17bad24d-6d05-4b29-8039-5782b5e5168a
langcode: en
dependencies:
  theme:
    - bartik
