id: theme.bartik.wide
name: wide
label: wide
mediaQuery: 'all and (min-width: 851px)'
source: bartik
sourceType: theme
weight: 2
multipliers:
  1x: 1x
status: true
uuid: 9f006525-6c00-42db-b200-a9e3a05c5d70
langcode: en
dependencies:
  theme:
    - bartik
