id: node.article.default
uuid: e1bc5d7e-4498-41f5-9009-09cb3eed12cf
targetEntityType: node
bundle: article
mode: default
content:
  field_image:
    label: hidden
    type: image
    settings:
      image_style: large
      image_link: ''
    weight: -1
  body:
    label: hidden
    type: text_default
    weight: 0
    settings: {  }
  field_tags:
    type: taxonomy_term_reference_link
    weight: 10
    label: above
    settings: {  }
  comment:
    label: hidden
    type: comment_default
    weight: 20
    settings:
      pager_id: '0'
hidden:
  langcode: true
  field_image: true
  field_tags: true
status: true
dependencies:
  entity:
    - field.instance.node.article.body
    - field.instance.node.article.comment
    - field.instance.node.article.field_image
    - field.instance.node.article.field_tags
    - node.type.article
  module:
    - comment
    - image
    - taxonomy
    - text
