id: node.page.default
uuid: c8efff7b-86b0-461f-b33f-63a6d0c32fd3
targetEntityType: node
bundle: page
mode: default
content:
  title:
    type: string
    weight: -5
    settings:
      size: 60
      placeholder: ''
  path:
    type: path
    weight: 30
    settings: {  }
  body:
    type: text_textarea_with_summary
    weight: 31
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
hidden: {  }
status: true
dependencies:
  entity:
    - field.instance.node.page.body
    - node.type.page
  module:
    - path
    - text
