id: node.article.teaser
uuid: 30122501-5848-4093-9d3a-58fc75d3b989
targetEntityType: node
bundle: article
mode: teaser
content:
  field_image:
    label: hidden
    type: image
    settings:
      image_style: medium
      image_link: content
    weight: -1
  body:
    label: hidden
    type: text_summary_or_trimmed
    weight: 0
    settings:
      trim_length: 600
  field_tags:
    type: taxonomy_term_reference_link
    weight: 10
    label: above
    settings: {  }
hidden:
  langcode: true
  field_image: true
  field_tags: true
  comment: true
status: true
dependencies:
  entity:
    - entity.view_mode.node.teaser
    - field.instance.node.article.body
    - field.instance.node.article.comment
    - field.instance.node.article.field_image
    - field.instance.node.article.field_tags
    - node.type.article
  module:
    - image
    - taxonomy
    - text
