id: user.user.default
uuid: bf8e06ed-7249-44cd-a004-4bf064a75320
targetEntityType: user
bundle: user
mode: default
content:
  account:
    weight: -10
  user_picture:
    type: image_image
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    weight: -1
  language:
    weight: 0
  contact:
    weight: 5
  timezone:
    weight: 6
hidden: {  }
status: true
dependencies:
  module:
    - image
    - user
