id: taxonomy_term.full
label: 'Taxonomy term page'
targetEntityType: taxonomy_term
status: false
cache: true
uuid: 373e8274-b690-464e-9900-b29ab3ddd12a
langcode: en
dependencies:
  module:
    - taxonomy
