id: node.blog.body
uuid: 1aee66d8-da19-4155-9727-393f35c5dcfc
status: true
langcode: en
field_uuid: 64933ccb-5006-403a-b700-b873a68e3907
field_name: body
entity_type: node
bundle: blog
label: Body
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  display_summary: true
  text_processing: true
dependencies:
  entity:
    - field.field.node.body
    - node.type.blog
field_type: text_with_summary
