id: comment.comment_body
uuid: 3538d4f7-b972-49aa-8731-49aad602f997
status: true
langcode: en
name: comment_body
entity_type: comment
type: text_long
settings: {  }
module: text
locked: false
cardinality: 1
translatable: false
indexes: {  }
dependencies:
  module:
    - comment
    - text
