id: node.field_blog_image
uuid: 92ab967e-a851-4fa2-881e-300f3b849536
status: true
langcode: en
name: field_blog_image
entity_type: node
type: image
settings:
  uri_scheme: public
  default_image:
    fid: 0
    alt: ''
    title: ''
    width: null
    height: null
  target_type: file
  display_field: 0
  display_default: 0
  target_bundle: null
module: image
locked: false
cardinality: 1
translatable: false
indexes: {  }
dependencies:
  module:
    - image
    - node
