id: node.article.field_tags
uuid: 318832f3-1e61-427f-9f00-eb905181475a
status: true
langcode: und
field_uuid: 9307c9ed-0025-4e82-9600-0e006d217398
field_name: field_tags
entity_type: node
bundle: article
label: Tags
description: 'Enter a comma-separated list. For example: Amsterdam, Mexico City, "Cleveland, Ohio"'
required: false
default_value: {  }
default_value_function: ''
settings:
  handler: default
dependencies:
  entity:
    - field.field.node.field_tags
    - node.type.article
field_type: taxonomy_term_reference
