format: full_html
name: 'Full HTML'
weight: 1
status: true
uuid: b0ef120c-78ab-4b68-9342-665a3d5f50bb
langcode: en
dependencies:
  module:
    - editor
filters:
  filter_caption:
    id: filter_caption
    provider: filter
    status: true
    weight: 9
    settings: {  }
  filter_htmlcorrector:
    id: filter_htmlcorrector
    provider: filter
    status: true
    weight: 10
    settings: {  }
  editor_file_reference:
    id: editor_file_reference
    provider: editor
    status: true
    weight: 11
    settings: {  }
  filter_autop:
    id: filter_autop
    provider: filter
    status: false
    weight: 0
    settings: {  }
  filter_html:
    id: filter_html
    provider: filter
    status: false
    weight: -10
    settings:
      allowed_html: '<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h4> <h5> <h6>'
      filter_html_help: true
      filter_html_nofollow: false
  filter_html_escape:
    id: filter_html_escape
    provider: filter
    status: false
    weight: -10
    settings: {  }
  filter_html_image_secure:
    id: filter_html_image_secure
    provider: filter
    status: false
    weight: 9
    settings: {  }
  filter_url:
    id: filter_url
    provider: filter
    status: false
    weight: 0
    settings:
      filter_url_length: 72
