name: medium
label: 'Medium (220x220)'
status: true
uuid: bae4958f-08c3-4f5c-8c00-b4aac812529a
langcode: en
dependencies: {  }
effects:
  bddf0d06-42f9-4c75-a700-a33cafa25ea0:
    uuid: bddf0d06-42f9-4c75-a700-a33cafa25ea0
    id: image_scale
    weight: 0
    data:
      width: 220
      height: 220
      upscale: true
