name: thumbnail
label: 'Thumbnail (100x100)'
status: true
uuid: 2281aa18-887c-4b60-9300-f35388fabd6f
langcode: en
dependencies: {  }
effects:
  1cfec298-8620-4749-b100-ccb6c4500779:
    uuid: 1cfec298-8620-4749-b100-ccb6c4500779
    id: image_scale
    weight: 0
    data:
      width: 100
      height: 100
      upscale: true
