type: article
name: Article
description: 'Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'
help: ''
title_label: Title
settings:
  node:
    options:
      status: true
      promote: true
      sticky: false
      revision: false
    preview: 1
    submitted: true
status: true
uuid: c84ca710-cd98-48a0-8e51-815591226af9
langcode: en
dependencies: {  }
