id: comment.comment
uuid: e57bd392-3bab-402e-a108-8f5680036a73
targetEntityType: comment
bundle: comment
types:
  - 'schema:Comment'
fieldMappings:
  subject:
    properties:
      - 'schema:name'
  created:
    properties:
      - 'schema:dateCreated'
    datatype_callback:
      callable: date_iso8601
  changed:
    properties:
      - 'schema:dateModified'
    datatype_callback:
      callable: date_iso8601
  comment_body:
    properties:
      - 'schema:text'
  uid:
    properties:
      - 'schema:author'
    mapping_type: rel
dependencies:
  entity:
    - comment.type.comment
  module:
    - comment
