id: node.page
uuid: 06ed9721-0516-4186-9700-f94ec21f9dd5
targetEntityType: node
bundle: page
types:
  - 'schema:WebPage'
fieldMappings:
  title:
    properties:
      - 'schema:name'
  created:
    properties:
      - 'schema:dateCreated'
    datatype_callback:
      callable: date_iso8601
  changed:
    properties:
      - 'schema:dateModified'
    datatype_callback:
      callable: date_iso8601
  body:
    properties:
      - 'schema:text'
  uid:
    properties:
      - 'schema:author'
    mapping_type: rel
  comment_count:
    properties:
      - 'schema:interactionCount'
    datatype_callback:
      callable: 'Drupal\rdf\SchemaOrgDataConverter::interactionCount'
      arguments:
        interaction_type: UserComments
dependencies:
  entity:
    - node.type.page
  module:
    - node
