id: node_promote_action
label: 'Promote content to front page'
status: true
uuid: 41485f11-20d8-423e-9308-8df4fa4740e9
langcode: en
dependencies:
  module:
    - node
type: node
plugin: node_promote_action
configuration: {  }
