id: user_add_role_action.administrator
label: 'Add the Administrator role to the selected users'
status: true
uuid: dd47cfd4-1ab9-4a3a-8300-f64d8e429bae
langcode: en
dependencies:
  entity:
    - user.role.administrator
  module:
    - user
type: user
plugin: user_add_role_action
configuration:
  rid: administrator
