id: node_make_sticky_action
label: 'Make content sticky'
status: true
uuid: 9b5cd85a-3c35-42bf-b94e-78b03dc2f60f
langcode: en
dependencies:
  module:
    - node
type: node
plugin: node_make_sticky_action
configuration: {  }
