id: comment_publish_action
label: 'Publish comment'
status: true
uuid: 15429212-4a15-4a40-9008-8ec15f55fe36
langcode: en
dependencies:
  module:
    - comment
type: comment
plugin: comment_publish_action
configuration: {  }
