id: user_remove_role_action.administrator
label: 'Remove the Administrator role from the selected users'
status: true
uuid: 7acce74d-b433-4acd-bf06-6b25a942da58
langcode: en
dependencies:
  entity:
    - user.role.administrator
  module:
    - user
type: user
plugin: user_remove_role_action
configuration:
  rid: administrator
