id: administrator
label: Administrator
weight: 2
permissions:
  - 'administer blocks'
  - 'administer comments'
  - 'administer comment types'
  - 'access comments'
  - 'post comments'
  - 'skip comment approval'
  - 'edit own comments'
  - 'synchronize configuration'
  - 'export configuration'
  - 'import configuration'
  - 'administer contact forms'
  - 'access site-wide contact form'
  - 'access user contact forms'
  - 'access contextual links'
  - 'administer display modes'
  - 'administer block_content fields'
  - 'administer block_content form display'
  - 'administer block_content display'
  - 'administer comment fields'
  - 'administer comment form display'
  - 'administer comment display'
  - 'administer contact_message fields'
  - 'administer contact_message form display'
  - 'administer contact_message display'
  - 'administer node fields'
  - 'administer node form display'
  - 'administer node display'
  - 'administer taxonomy_term fields'
  - 'administer taxonomy_term form display'
  - 'administer taxonomy_term display'
  - 'administer user fields'
  - 'administer user form display'
  - 'administer user display'
  - 'access files overview'
  - 'administer filters'
  - 'use text format basic_html'
  - 'use text format restricted_html'
  - 'use text format full_html'
  - 'administer image styles'
  - 'administer menu'
  - 'bypass node access'
  - 'administer content types'
  - 'administer nodes'
  - 'access content overview'
  - 'access content'
  - 'view own unpublished content'
  - 'view all revisions'
  - 'revert all revisions'
  - 'delete all revisions'
  - 'create article content'
  - 'edit own article content'
  - 'edit any article content'
  - 'delete own article content'
  - 'delete any article content'
  - 'view article revisions'
  - 'revert article revisions'
  - 'delete article revisions'
  - 'create page content'
  - 'edit own page content'
  - 'edit any page content'
  - 'delete own page content'
  - 'delete any page content'
  - 'view page revisions'
  - 'revert page revisions'
  - 'delete page revisions'
  - 'administer url aliases'
  - 'create url aliases'
  - 'access in-place editing'
  - 'administer search'
  - 'search content'
  - 'use advanced search'
  - 'administer shortcuts'
  - 'customize shortcut links'
  - 'switch shortcut sets'
  - 'access shortcuts'
  - 'administer modules'
  - 'administer site configuration'
  - 'administer themes'
  - 'administer software updates'
  - 'access administration pages'
  - 'access site in maintenance mode'
  - 'view the administration theme'
  - 'access site reports'
  - 'administer taxonomy'
  - 'edit terms in tags'
  - 'delete terms in tags'
  - 'access toolbar'
  - 'access tour'
  - 'administer permissions'
  - 'administer account settings'
  - 'administer users'
  - 'access user profiles'
  - 'change own username'
  - 'cancel account'
  - 'select account cancellation method'
  - 'administer views'
  - 'access all views'
status: true
uuid: 89caaae0-c588-4f29-b200-ed08b4c75478
langcode: en
dependencies: {  }
